# .github/workflows/build-windows.yml

name: Build Windows Executable

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller socketio pyperclip

    - name: Build Windows Executable
      run: |
        pyinstaller --onefile --windowed uptime_kuma_token.py

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: dist/uptime_kuma_token.exe
